# fly.toml app configuration file generated for messaging-app-thrumming-wildflower-8588 on 2023-12-31T17:07:46-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messaging-app-thrumming-wildflower-8588"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
